# Generated by Django 3.2.6 on 2024-07-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
